version: '3'

services:
  mongodb:
    container_name: mongodb
    # image: bitnami/mongodb:6.0
    image: mongo:4.2.23-bionic
    platform: 'linux/x86_64'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    extra_hosts:
      - docker.for.mac.host.internal:host-gateway
      - docker.for.win.host.internal:host-gateway
    environment:
      #=================== jika menggunakan bitnami image =========
      # - MONGODB_ROOT_PASSWORD=mongodb
      # - MONGODB_USERNAME=mongodb
      # - MONGODB_PASSWORD=mongodb
      # - MONGODB_DATABASE-mongodb
      # - MONGODB_PORT_NUMBER=27017
      # - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      # - MONGODB_DISABLE_SYSTEM_LOG=false
      # - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      # ================= jika menggunakan official mongo ========
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    networks:
      - net-mongo
      - external-network
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
      PORT: "8082"
    ports:
      - "0.0.0.0:8082:8081"
    depends_on:
      - mongodb
    networks:
      - net-mongo
      - external-network

volumes:
  mongodb_data:
    driver: local

networks:
  external-network:
    external: true
  net-mongo:
    driver: bridge
  
