version: '3'

services:
  mysql:
    image: mysql:8.0
    # image: mysql:5.7
    platform: 'linux/x86_64'
    container_name: mysql
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - external-network
      - net-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: 'linux/x86_64'
    restart: 'always'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
    networks:
      - external-network
      - net-mysql

networks:
  external-network:
    external: true
  net-mysql:
    driver: bridge