version: '3'

services:
  postgres:
    container_name: postgres
    restart: always
    platform: linux/x86_64
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - net-postgres
      - external-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8084:8080
    networks:
      - net-postgres
      - external-network

networks:
  external-network:
    external: true
  net-postgres:
    driver: bridge

volumes:
  dbdata:
  