version: '3'

services:
  postgres:
    container_name: postgres
    restart: always
    platform: linux/x86_64
    image: bitnami/postgresql:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    networks:
      - net-postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8084:8080
    networks:
      - net-postgres

networks:
  net-postgres:
    driver: bridge