version: '3'

services:
  redis:
    image: bitnami/redis:6.2.11
    container_name: redis
    platform: 'linux/x86_64'
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/redis
    networks:
      - external-network
      - net-redis

networks:
  external-network:
    external: true
  net-redis:
    driver: bridge
  
