version: '3'

services:
  redis:
    image: redis:6.2
    # image: bitnami/redis:7.2
    container_name: redis
    platform: 'linux/x86_64'
    # restart: always
    # environment:
    #   - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/redis
    # command: redis-server --appendonly yes --requirepass redis # untuk image redis
    networks:
      - external-network
      - net-redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    depends_on:
      - redis
    # restart: always
    environment:
    - REDIS_HOSTS=redis
    # - REDIS_PASSWORD=redis
    ports:
    - "8081:8081"
    networks:
      - external-network
      - net-redis

networks:
  external-network:
    external: true
  net-redis:
    driver: bridge
  
